In [1]:
import numpy as np

# Fatoração de Cholesky

In [4]:
def Cholesky(A):
    p = 0
    L = np.zeros_like(A, dtype=np.float64)
    n = A.shape[0]
    for k in range(n):
        summation = 0
        for j in range(k):
            summation += L[k][j] ** 2

        summation = A[k, k] - summation
        if summation <= 0:
            p = 1
            print("Matrix A não é definida positiva.")

        L[k, k] = np.sqrt(summation)
        for i in range(k+1, n):
            summation = 0
            for j in range(k):
                summation += L[i][j] * L[k][j]
            
            L[i][k] = (A[i][k] - summation)/L[k][k]

    return L, p

## Funções de Validação

In [5]:
def Cholesky_validation(A):
    if np.array_equal(Cholesky(A)[0], np.linalg.cholesky(A)):
        print("Fatoração Cholesky está correta")
    else:
        print("Ocorreu um erro na Fatoração Cholesky")
Cholesky_validation(A)

def definida_positiva(A):
    if Cholesky(A)[1] == 0:
        print("A é definida positiva")
    else:
        print("A não é definida positiva")

definida_positiva(A)

Fatoração Cholesky está correta
A é definida positiva


# Exercício 1
A = $\begin{bmatrix} 1 & 1 & 1 \\ 1 & 2 & 3 \\ 1 & 3 & 6 \end{bmatrix}$


In [6]:
A = np.array([[1,1,1],[1,2,3],[1,3,6]])
A

array([[1, 1, 1],
       [1, 2, 3],
       [1, 3, 6]])

In [7]:
L, p = Cholesky(A)
L

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 2., 1.]])

In [8]:
Cholesky_validation(A)
definida_positiva(A)

Fatoração Cholesky está correta
A é definida positiva


# Exercício 2
## Part 1
Validar matrix de pascal A apresentada \
\
A = $\begin{bmatrix} 1 & 1 & 1 & 1 & 1  \\ 1 & 2 & 3 & 4 & 5\\ 1 & 3 & 6 & 10 & 15 \\ 1 & 4 & 10 & 20 & 35 \\ 1 & 5 & 15 & 35 & 70\end{bmatrix}$


In [9]:
A = np.array([[1,1,1,1,1],[1,2,3,4,5],[1,3,6,10,15],[1,4,10,20,35],[1,5,15,35,70]])
A

array([[ 1,  1,  1,  1,  1],
       [ 1,  2,  3,  4,  5],
       [ 1,  3,  6, 10, 15],
       [ 1,  4, 10, 20, 35],
       [ 1,  5, 15, 35, 70]])

In [10]:
L,p = Cholesky(A)
L

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 2., 1., 0., 0.],
       [1., 3., 3., 1., 0.],
       [1., 4., 6., 4., 1.]])

In [11]:
Cholesky_validation(A)
definida_positiva(A)

Fatoração Cholesky está correta
A é definida positiva


# Exercício 2
## Part 2
Validar matrix de pascal A apresentada trocando o valor de a[3][3] = 6 por a[3][3] = 5  \
\
A_ = $\begin{bmatrix} 1 & 1 & 1 & 1 & 1  \\ 1 & 2 & 3 & 4 & 5\\ 1 & 3 & 5 & 10 & 15 \\ 1 & 4 & 10 & 20 & 35 \\ 1 & 5 & 15 & 35 & 70\end{bmatrix}$


In [12]:
A_ = np.array([[1,1,1,1,1],[1,2,3,4,5],[1,3,5,10,15],[1,4,10,20,35],[1,5,15,35,70]])
A_

array([[ 1,  1,  1,  1,  1],
       [ 1,  2,  3,  4,  5],
       [ 1,  3,  5, 10, 15],
       [ 1,  4, 10, 20, 35],
       [ 1,  5, 15, 35, 70]])

In [13]:
L,p = Cholesky(A_)
L

Matrix A não é definida positiva.
Matrix A não é definida positiva.


/var/folders/zn/rfsv9ts17k3fzwd8pvt9h30r0000gn/T/ipykernel_83088/4097488180.py:21: RuntimeWarning: divide by zero encountered in double_scalars
  L[i][k] = (A[i][k] - summation)/L[k][k]
/var/folders/zn/rfsv9ts17k3fzwd8pvt9h30r0000gn/T/ipykernel_83088/4097488180.py:15: RuntimeWarning: invalid value encountered in sqrt
  L[k, k] = np.sqrt(summation)


array([[ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.],
       [ 1.,  2.,  0.,  0.,  0.],
       [ 1.,  3., inf, nan,  0.],
       [ 1.,  4., inf, nan, nan]])

In [14]:
## Ocorre erro como esperado, pois a alteração desse valor tornou a matrix não definida positiva
definida_positiva(A_)
Cholesky_validation(A_)

Matrix A não é definida positiva.
Matrix A não é definida positiva.
A não é definida positiva
Matrix A não é definida positiva.
Matrix A não é definida positiva.


/var/folders/zn/rfsv9ts17k3fzwd8pvt9h30r0000gn/T/ipykernel_83088/4097488180.py:21: RuntimeWarning: divide by zero encountered in double_scalars
  L[i][k] = (A[i][k] - summation)/L[k][k]
/var/folders/zn/rfsv9ts17k3fzwd8pvt9h30r0000gn/T/ipykernel_83088/4097488180.py:15: RuntimeWarning: invalid value encountered in sqrt
  L[k, k] = np.sqrt(summation)


LinAlgError: Matrix is not positive definite

# Referência

- Referencia: 
    - Ruggiero, M.A.G. e Lopes, V.L.R., Calculo Numérico - Aspectos Teóricos e Computacionais, Segunda Edição, Pearson, 2000.
    - IA897 Unicamp, Prof. Paulo Valente