In [2]:
import numpy as np

# Fatoração QR

In [8]:
def qr(A):
    n = A.shape[0] # .shape Obtém a dimensão da matriz e shape[0] diz o número de linhas
    R = A.copy().astype(float)
    Q = np.eye(n) # np.eye cria uma matriz identidade de tamanho n x n
    
    for j in range(n-1):
        x = R[j:, j] # Extrai a subcoluna a partir da posição j,j
        
        if x[0] >= 0:
            sign = -1
        else: 
            sign = 1
        s_j = sign * np.linalg.norm(x) # np.linalg.norm calcula a norma Euclidiana do vetor x
        
        if np.isclose(s_j, 0): # Verifica se s_j é próximo de zero (tolerância numérica)
            continue 
        
        v = x.copy()
        v[0] = v[0] - s_j
        w = v / np.linalg.norm(v)
        
        P = np.eye(n - j) - 2 * np.outer(w, w)
        
        # @ é o operador de multiplicação de matrizes no Python
        R[j:, j:] = P @ R[j:, j:]
        Q[:, j:] = Q[:, j:] @ P.T
    
    return Q, R


In [18]:
def compare_matrices_with_tolerance(A, B, tolerance=1e-10):
    if np.allclose(A, B, atol=tolerance): # np.allclose compara duas matrizes com tolerância especificada
        print('As matrizes são idênticas!')


In [20]:
def pascal_matrix(n):
    A = np.ones((n, n)) # np.ones cria matriz n x n preenchida com 1s
    for i in range(1, n):
        for j in range(1, n):
            A[i, j] = A[i-1, j] + A[i, j-1]
    return A

In [21]:
A = pascal_matrix(6)
print("Matriz de Pascal A (6x6):")
print(A)

Q, R = qr(A)
Q_numpy, R_numpy = np.linalg.qr(A)

compare_matrices_with_tolerance(Q, Q_numpy)
compare_matrices_with_tolerance(R, R_numpy)

Matriz de Pascal A (6x6):
[[  1.   1.   1.   1.   1.   1.]
 [  1.   2.   3.   4.   5.   6.]
 [  1.   3.   6.  10.  15.  21.]
 [  1.   4.  10.  20.  35.  56.]
 [  1.   5.  15.  35.  70. 126.]
 [  1.   6.  21.  56. 126. 252.]]
As matrizes são idênticas!
As matrizes são idênticas!


In [22]:
print("Matriz Q:")
print(np.round(Q, 6))
print()

print("Matriz R:")
print(np.round(R, 6))
print()

Matriz Q:
[[-0.408248 -0.597614  0.545545 -0.372678  0.188982 -0.062994]
 [-0.408248 -0.358569 -0.109109  0.521749 -0.566947  0.31497 ]
 [-0.408248 -0.119523 -0.436436  0.298142  0.377964 -0.629941]
 [-0.408248  0.119523 -0.436436 -0.298142  0.377964  0.629941]
 [-0.408248  0.358569 -0.109109 -0.521749 -0.566947 -0.31497 ]
 [-0.408248  0.597614  0.545545  0.372678  0.188982  0.062994]]

Matriz R:
[[-2.44949000e+00 -8.57321400e+00 -2.28619040e+01 -5.14392850e+01
  -1.02878569e+02 -1.88610710e+02]
 [-0.00000000e+00  4.18330000e+00  1.67332010e+01  4.51796410e+01
   1.00399203e+02  1.97212721e+02]
 [-0.00000000e+00  0.00000000e+00  3.05505000e+00  1.37477270e+01
   3.92792200e+01  9.00148800e+01]
 [ 0.00000000e+00  0.00000000e+00 -0.00000000e+00  1.34164100e+00
   6.70820400e+00  2.04972900e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
   3.77964000e-01  2.07880500e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  6.29940000

In [23]:
print("A:")
print(np.round(A, 6))
print()

A_reconstructed = Q @ R 
print("QR:")
print(np.round(A_reconstructed, 6))
print()

A:
[[  1.   1.   1.   1.   1.   1.]
 [  1.   2.   3.   4.   5.   6.]
 [  1.   3.   6.  10.  15.  21.]
 [  1.   4.  10.  20.  35.  56.]
 [  1.   5.  15.  35.  70. 126.]
 [  1.   6.  21.  56. 126. 252.]]

QR:
[[  1.   1.   1.   1.   1.   1.]
 [  1.   2.   3.   4.   5.   6.]
 [  1.   3.   6.  10.  15.  21.]
 [  1.   4.  10.  20.  35.  56.]
 [  1.   5.  15.  35.  70. 126.]
 [  1.   6.  21.  56. 126. 252.]]

